function [rho_rr, rho_ii, rho_ri] = recover_correlation_b( ...
    M, coeff, R_rr, R_ii, R_ri, nmax, tol, max_iter)
[rho_rr, rho_ii, rho_ri] = recover_correlation_from_coeff( ...
    M, coeff, R_rr, R_ii, R_ri, nmax, tol, max_iter);
end
